### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by lerous** [lackofcheese/ZeldaMapper#5]
I'm really interested in your project, but I don't know how to compile 'mapper.py' (already installed PIL).

eg What's the syntax of 'settings.cfg'? Do I need to run the rom in fceux first? 

Need a step-by-step please, thanks.

**Comment by lackofcheese** [comment]
Hi lerous,

I'm glad to see someone else might want to use this! It's been a while since I've used it, but I checked it and it still works OK.

I've updated the documentation in response to your questions, so I think things should be a bit clearer now. See the README on the main page
https://github.com/lackofcheese/ZeldaMapper
for details.

As a quick answer to the questions you raise above:
- mapper.py shouldn't need to be compiled; it's an executable Python script which should be run from the command line.
- settings.cfg roughly follows the INI file format; that is, zero or more sections starting with a [section] header, containing key-value pairs and comments on lines starting with # characters. If you need more details, the python configparser library goes into details on the file format here:
  https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

**Comment by lackofcheese** [comment]
I think the current how-to on the main page should be good enough now, so I'll close the issue for the moment.
